<a href="https://colab.research.google.com/github/JennEYoon/code/blob/main/current/numpy4_struct.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Quick Practice, numpy4, structured array  

In [ ]:
# numpy4, quick practice  
# Structured Arrays in numpy  
# Data start Jan 18, 2022 1:30 pm  
# 4:30 pm restart, 7 pm stop  
# Github repo: "code" folder "current" file "numpy4_structured.py"  

import numpy as np 
np

<module 'numpy' from '/usr/local/lib/python3.7/dist-packages/numpy/__init__.py'>

In [ ]:
# Structured Array data type  
# Only data type that can have strings in a numpy cell.
            
data = {'person':['Mary', "Jisoo", "Kevin", "Craig"], 
        'weight':[125.5, 105.3, 163.2, 180.9], 
        'id':[101, 102, 55, 56]}
print(data, type(data))

{'person': ['Mary', 'Jisoo', 'Kevin', 'Craig'], 'weight': [125.5, 105.3, 163.2, 180.9], 'id': [101, 102, 55, 56]} <class 'dict'>


In [ ]:
# mat = np.structured(data=data, dtype={'person': 'string', 'age':'float16', 'id':'uint'})     
# Not sure about name of function for structured array  
# Not sure about format      

# First create an empty container with compound data types
# Then fill with data, each item is a list.

tp = np.dtype({'names':('person', 'weight', 'id'), 'formats':('U10', 'f8', 'u1')})
# had extra =.  tp = np.dtype=(...)  Redefined all dtypes into this one custome type!
# each items are tuples, so ( ) and not list [ ]
X = np.zeros(4, dtype=tp) 
# 4 rows, each with 3 columns  
print(X, type(X), '\n')

X['person'] = data['person']
X['weight'] = data['weight']
X['id'] = data['id']
print(X, type(X), '\n')

print("4th record: ", X[3], "Name: ", X[3]['person'])

[('', 0., 0) ('', 0., 0) ('', 0., 0) ('', 0., 0)] <class 'numpy.ndarray'> 

[('Mary', 125.5, 101) ('Jisoo', 105.3, 102) ('Kevin', 163.2,  55)
 ('Craig', 180.9,  56)] <class 'numpy.ndarray'> 

4th record:  ('Craig', 180.9, 56) Name:  Craig


In [ ]:
# Try in one go  
Y = np.array(data)
print(Y, type(Y))
# Somehow it remembered custom dtype and applied it.  
# OK, the new dtype is in memory, as a current run-time variable.  

{'person': ['Mary', 'Jisoo', 'Kevin', 'Craig'], 'weight': [125.5, 105.3, 163.2, 180.9], 'id': [101, 102, 55, 56]} <class 'numpy.ndarray'>


In [ ]:
# original data, still in dictionary type
print(data, type(data))

{'person': ['Mary', 'Jisoo', 'Kevin', 'Craig'], 'weight': [125.5, 105.3, 163.2, 180.9], 'id': [101, 102, 55, 56]} <class 'dict'>


### Need to restart runtime, No, extra "=" in definition 

Can't figure out how to clear memory of new data type, np.dtype=None does not work.  
All future numpy operations expect the new data type, np.dtype.  

In [ ]:
import numpy as np

# Second structured array
tp2 = np.dtype({'names':('states', 'ab', 'incomes', 'num'), 'formats':('U10', 'U4', 'i4', 'f8')})
Z = np.zeros(4, dtype=tp2)
Z

array([('', '', 0, 0.), ('', '', 0, 0.), ('', '', 0, 0.), ('', '', 0, 0.)],
      dtype=[('states', '<U10'), ('ab', '<U4'), ('incomes', '<i4'), ('num', '<f8')])

In [ ]:
# Define another structured numpy array  
states = ['Colorado', 'Virginia', 'Maryland', 'Alaska']
ab = ['CO', 'VA', 'MD', 'AL']
incomes = [103000, 130000, 115999, 56000]

ranks = [3, 1, 2, 4]
rng = np.random.seed(100)
num = np.random.random(4)
print(num)

[0.54340494 0.27836939 0.42451759 0.84477613]


In [ ]:
Z['states'] = states
Z['ab'] = ab
Z['incomes'] = incomes
Z['num'] = num
print(Z)

[('Colorado', 'CO', 103000, 0.54340494)
 ('Virginia', 'VA', 130000, 0.27836939)
 ('Maryland', 'MD', 115999, 0.42451759)
 ('Alaska', 'AL',  56000, 0.84477613)]


In [ ]:
print(Z[2], type(Z[2]))

('Maryland', 'MD', 115999, 0.42451759) <class 'numpy.void'>


In [ ]:
z2 = np.zeros(4, dtype=({'names':('states', 'ranks'), 'formats':('U8', 'i4')}))
print(z2)

[('', 0) ('', 0) ('', 0) ('', 0)]


In [ ]:
z2['states'] = states
z2['ranks'] = ranks 
print(z2)

[('Colorado', 3) ('Virginia', 1) ('Maryland', 2) ('Alaska', 4)]


### More exercises, random 

In [ ]:
A = np.ones((3, 5), dtype='float32')
# expect 3 row x 5 col matrix of floating point 1.'s.  
print("ones: \n", A, type(A), '\n')

# B = np.random.random((3, 5), dtype='float16') 
# expect 3 row x 5 col matrix, random numbers (0, 1) uniform distribution  
# no type attribute for random generator. Returns float always. 
#  B = np.random.random(3,5) # row x col needs to be a single object, inside ().
B = np.random.random((3, 5))
print("randome: \n", B, type(B), '\n')

# C = np.random.normal((3, 3), (0, 3))      
# expect 3 x 3 matric, random numbers from (mu=0, sigma=+/- 3) normal distribution  
# ex: np.random.normal(3, 2.5, size=(2, 4))
# np.random.normal(mu, sigma, size=(row, col))

C = np.random.normal(0, 6, size=(3, 5))
print("normal dist: \n", C, type(C))

ones: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] <class 'numpy.ndarray'> 

randome: 
 [[0.00471886 0.12156912 0.67074908 0.82585276 0.13670659]
 [0.57509333 0.89132195 0.20920212 0.18532822 0.10837689]
 [0.21969749 0.97862378 0.81168315 0.17194101 0.81622475]] <class 'numpy.ndarray'> 

normal dist: 
 [[-3.00848076 -9.95221702 -6.04546378 -3.05240659  4.68893052]
 [-3.9262862   0.24703481 -1.21150144 -5.2248789   1.37359242]
 [-2.44823965 -0.62355083  9.40307271  2.98214829  6.93523401]] <class 'numpy.ndarray'>


In [ ]:
# random with reshape  
R = np.random.random(16)
R


array([0.02043913, 0.21002658, 0.54468488, 0.76911517, 0.25069523,
       0.28589569, 0.85239509, 0.97500649, 0.88485329, 0.35950784,
       0.59885895, 0.35479561, 0.34019022, 0.17808099, 0.23769421,
       0.04486228])

In [ ]:
R2 = np.random.randint(-10, 10, 16)
R3 = R2.reshape(2, 8)
R3

array([[ -8,   0,   8,   3,   2,  -9,  -4,   0],
       [-10,  -8,   9,  -6,   8,  -6,  -7,  -1]])