<a href="https://colab.research.google.com/github/JennEYoon/code/blob/main/current/numpy3a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy practice 3a   
linked private Github repo: "code"   
Jan 4, 2022  

In [ ]:
# CoLab quick practice file  
# Numpy practice 3 
# code repo, private dev  
# Jan 4, 2022  
# Create matrix  

# A = np.ones().reshape(3, 3)  
# forgot number of items in np.ones().
A = np.ones(9).reshape(3, 3)  

print(A, type(A))  
# expect ndarray type, [[1,1,1], [1,1,1], [1,1,1]]

# B = np.array([1,2,3], [4,5,6], [7,8,9])
# TypeError: array() takes from 1 to 2 positional arguments but 3 were given 
B = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)

print(B, type(B)) 
# expect ndarray type, [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  

#print(A.shape(), B.shape())
#TypeError: 'tuple' object is not callable
print(np.shape(A), np.shape(B))
# expect 3x3 3x3  



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
(3, 3) (3, 3)


### Evaluation:  
Error on all 3 parts, but only 1 error.  Was able to fix after reading error message in 1-2 tries each.  Yeah!!!  
Was worthy exercise since I could not remember how to do it correctly on first try.  

In [ ]:
# Try nested list and turn it into numpy array.  Probably will fail.  
import numpy as np

clist = [[10, 11, 12], [20, 21, 22], [30, 31, 32]]

C = np.array(clist)  # expect error
print(C, type(C))  # Worked!  Unexpected.  

# D = np.AsArray(clist)  # maybe will work?  
# Wrong capitals
D = np.asarray(clist)
print(D, type(D))  # Works!  Wow.  

E = np.asarray( [[10, 11, 12], [20, 21, 22], [30, 31, 32]] )
print(E, type(E))

F = np.array([[10, 11, 12], [20, 21, 22], [30, 31, 32]])
print("F:", F, type(F))

[[10 11 12]
 [20 21 22]
 [30 31 32]] <class 'numpy.ndarray'>
[[10 11 12]
 [20 21 22]
 [30 31 32]] <class 'numpy.ndarray'>
[[10 11 12]
 [20 21 22]
 [30 31 32]] <class 'numpy.ndarray'>
F: [[10 11 12]
 [20 21 22]
 [30 31 32]] <class 'numpy.ndarray'>


### Evaluation, nested list works!  
Tried different combinations of nested lists, 
to turn them into numpy ndarray, they all worked!  Not expecting this.  

In [6]:
# Try using random to create ndarray. 

import numpy as np
#from random import randint, choice, shuffle, randrange
import random

mat = np.arange(0,100, 5)
print(mat, len(mat))


[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95] 20


In [7]:
b = random.choice(mat)
print(b)

85


In [10]:
c = np.random.choice(mat)
print(c)

40
