<a href="https://colab.research.google.com/github/JennEYoon/code/blob/main/current/numpy_at.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np  

A = np.array([5, 6, 7, 8, 9])
B = np.arange(0, 15, 3)  
print(A, B)

[5 6 7 8 9] [ 0  3  6  9 12]


In [ ]:
A + B

array([ 5,  9, 13, 17, 21])

In [ ]:
A * B

array([  0,  18,  42,  72, 108])

In [ ]:
A @ B

240

In [ ]:
# 1x5 * 5x1 = 1x1 dimension. 

In [ ]:
# matrix multiplication @ infix operator. A @ B. 
C = np.array([[1, 1], [-1, -1]])
D = np.array([[1, 1], [4, 4]])
print(C, D)
result = C @ D.T
print(result)

[[ 1  1]
 [-1 -1]] [[1 1]
 [4 4]]
[[ 2  8]
 [-2 -8]]


In [ ]:
# nxm @ mxn = nxn  
# [(1*1 + 1*1), (1*4 + 1*4), 
#  (-1*1 + -1*1), (-1*4 + -1*4)]
# 