### Numpy practice 3 
code repo, private dev  
Jan 4, 2022  

In [4]:

# Numpy practice 3 
# code repo, private dev  
# Jan 4, 2022  
# Create matrix  

# A = np.ones().reshape(3, 3)  
# forgot number of items in np.ones().
A = np.ones(9).reshape(3, 3)  

print(A, type(A))  
# expect ndarray type, [[1,1,1], [1,1,1], [1,1,1]]

# B = np.array([1,2,3], [4,5,6], [7,8,9])
# TypeError: array() takes from 1 to 2 positional arguments but 3 were given 
B = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9]).reshape(3, 3)

print(B, type(B)) 
# expect ndarray type, [[1, 2, 3], [4, 5, 6], [7, 8, 9]]  

#print(A.shape(), B.shape())
#TypeError: 'tuple' object is not callable
print(np.shape(A), np.shape(B))
# expect 3x3 3x3  



[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>
(3, 3) (3, 3)


### Evaluation:  
Error on all 3 parts, but only 1 error.  Was able to fix after reading error message in 1-2 tries each.  Yeah!!!  
Was worthy exercise since I could not remember how to do it correctly on first try.  