# JY-vanderplas-numpy
date: 7/17/2019 1:14 AM  
    duplicate knn 2D sample.
    KNN starts on p88. (Part of nb S2.8 Sorting)  
    
## Sorting Arrays, nb S2.08, p.85 of VanderPlas  
    insertion sort, selection sort, merge sort, quick sort, bubble sort, etc.    

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
%matplotlib inline

In [2]:
np
# conda environment pyfin activated.
np.__version__
# '1.16.4'

'1.16.4'

## Creating Arrays, numpy

In [3]:
# List object
L = range(10)
print(type(L))
print(L)

<class 'range'>
range(0, 10)


In [4]:
list1 = [3,1,0,7,9]
print(list1)
print(type(list1))

[3, 1, 0, 7, 9]
<class 'list'>


In [5]:
arr1 = np.array(list1)
arr1

array([3, 1, 0, 7, 9])

In [6]:
list1.append(11)
list1
# [3, 1, 0, 7, 9, 11, 11]

[3, 1, 0, 7, 9, 11]

In [7]:
arr1
#  Makes a copy, new np object.
#  Changes to list1 does not change np object.
# array([3, 1, 0, 7, 9])

array([3, 1, 0, 7, 9])

In [8]:
z = list1 + list(arr1)
z

[3, 1, 0, 7, 9, 11, 3, 1, 0, 7, 9]

In [9]:
arr1
type(arr1)
list2 = list1[0:5]

In [10]:
arr2 = (arr1 + np.array(list2))
arr2

array([ 6,  2,  0, 14, 18])

In [11]:
list4 = [range(i, i+6) for i in [10, 20, 30, 40]]
# creates list using built-in "range() function."
# start at i (10, 20,..), and stop at i+5 (15, 25, ...)
print(list4)
print(type(list4))

[range(10, 16), range(20, 26), range(30, 36), range(40, 46)]
<class 'list'>


In [17]:
list3 = list4

In [18]:
np.array(list3)

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

In [19]:
np.array(list4)

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45]])

In [20]:
sum3 = np.array(list3) + np.array(list4)
sum3

array([[20, 22, 24, 26, 28, 30],
       [40, 42, 44, 46, 48, 50],
       [60, 62, 64, 66, 68, 70],
       [80, 82, 84, 86, 88, 90]])

In [21]:
mul2 = np.array(list3) * np.array(list4)
mul2

array([[ 100,  121,  144,  169,  196,  225],
       [ 400,  441,  484,  529,  576,  625],
       [ 900,  961, 1024, 1089, 1156, 1225],
       [1600, 1681, 1764, 1849, 1936, 2025]])

## np.zeros, np.ones, np.full, np.arange(start, stop, step)

In [24]:
arrz = np.zeros(10, dtype=int)
arrz

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
arrone = np.ones((3, 5), dtype='float32')
arrone

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)

In [33]:
import math
print(math.pi)
arrfull = np.full((4, 6), math.pi, dtype='float32')
print(arrfull)

3.141592653589793
[[3.1415927 3.1415927 3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927 3.1415927 3.1415927]
 [3.1415927 3.1415927 3.1415927 3.1415927 3.1415927 3.1415927]]


In [34]:
arrfull2 = np.full((3, 3), 3.14159, dtype=float)
print(arrfull2)

[[3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159]
 [3.14159 3.14159 3.14159]]


In [35]:
# linear sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [36]:
# reshape into 3 x 5.
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [37]:
# evenly spaced line, useful for x-axis.
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [38]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random numbered array generator

In [40]:
# uniform distribution (0, 1).
result = np.random.random((3, 5))
print("2D: ", result)
# single parenthesis for 1D.
result2 = np.random.random(20)
print("1D: ", result2)

2D:  [[0.31503752 0.71635529 0.0405571  0.01299294 0.58926139]
 [0.84328966 0.97591215 0.37428523 0.75756528 0.98676847]
 [0.05552297 0.39566296 0.2730506  0.40199142 0.63065369]]
1D:  [0.2948853  0.12363901 0.03708783 0.17256779 0.50048843 0.452798
 0.08999549 0.82133019 0.04131933 0.66712977 0.39777827 0.07909316
 0.00581841 0.06535168 0.15446152 0.91723359 0.9622743  0.18278401
 0.61637578 0.73462347]


In [42]:
result3 = np.random.random(((4, 5, 2)))
print(result3)

[[[0.79686505 0.16743014]
  [0.05813194 0.12990645]
  [0.41562329 0.07125647]
  [0.70901007 0.2379681 ]
  [0.42440724 0.70801794]]

 [[0.67893188 0.79018752]
  [0.82024173 0.82112997]
  [0.81484076 0.4892616 ]
  [0.2942677  0.9245694 ]
  [0.68531772 0.82400766]]

 [[0.68369565 0.26566254]
  [0.95398769 0.12694255]
  [0.12892243 0.48144126]
  [0.1310274  0.26250092]
  [0.09956561 0.92822734]]

 [[0.48457188 0.55457117]
  [0.45553356 0.65589051]
  [0.56862649 0.09811512]
  [0.89418867 0.43806025]
  [0.5216787  0.39206504]]]


In [43]:
result4 = np.random.random((((2, 3, 4, 5))))  
# Outermost bracket, next inner bracket, next inner bracket (rows), no bracket (column data points).
print(result4)

[[[[0.8696514  0.23209663 0.85389149 0.14007183 0.70186316]
   [0.74757082 0.02806154 0.03697738 0.48415527 0.0930922 ]
   [0.14860813 0.86718633 0.6460759  0.01997612 0.66955209]
   [0.26445988 0.535115   0.63758994 0.49509107 0.75671355]]

  [[0.66362063 0.30544758 0.11491333 0.8622364  0.21063314]
   [0.45138326 0.21572956 0.31086463 0.42454032 0.20436546]
   [0.35954299 0.7428318  0.68793619 0.96782539 0.97855823]
   [0.93341759 0.65652675 0.29257141 0.2853523  0.85719152]]

  [[0.05548086 0.56867696 0.14229185 0.86597055 0.31644431]
   [0.56086596 0.11779504 0.89061696 0.75922434 0.74318457]
   [0.87463691 0.80628447 0.3093479  0.44685683 0.95746057]
   [0.04207852 0.8677439  0.03632989 0.49908177 0.56615681]]]


 [[[0.31563787 0.92924618 0.43861196 0.74812504 0.53056924]
   [0.81020524 0.80410043 0.46613252 0.76872781 0.62024211]
   [0.73773694 0.16220102 0.26845666 0.93562074 0.43130301]
   [0.74494238 0.40580995 0.32999223 0.9558178  0.92080911]]

  [[0.2545957  0.70603822 0.31

In [44]:
np.random.normal(0, 1, (3, 4))

array([[-0.37848019,  0.65800455, -0.5371275 ,  0.15394308],
       [-1.46979235, -0.88987903,  0.29696751,  0.01397883],
       [ 0.43695764, -0.32447179,  0.55192596, -0.22843575]])

In [46]:
np.random.normal(100, 3, (5, 5))

array([[ 96.50536689, 101.29322073, 101.1587553 , 101.17739815,
        101.48280804],
       [ 97.10479084,  97.5134279 ,  97.58555352, 105.0600146 ,
         96.49088169],
       [103.38961159, 101.71692974, 103.44016687,  93.54023114,
         97.95507993],
       [ 97.91376868,  96.72616154, 106.30507311,  96.6025693 ,
        101.29423374],
       [106.48370877,  98.67566268,  96.13611825,  98.29495336,
         98.66766171]])

In [47]:
np.random.random?

In [49]:
# To sample :math:`Unif[a, b), b > a` multiply
# the output of `random_sample` by `(b-a)` and add `a`.
#
#  (b - a) * random_sample() + a

# Sample [1, 5)
result5 =  4 * np.random.random((3, 3)) + 1
result5

array([[3.74509097, 1.58690678, 3.27257222],
       [4.11277956, 4.56625713, 1.96277307],
       [1.0680932 , 3.14563573, 2.83044403]])

In [50]:
# Sample [-5, 5)
result6 =  10 * np.random.random((3, 3)) - 5
result6

array([[-3.16672505, -4.75076174,  2.50851333],
       [ 4.50659805, -2.51615883, -2.63480349],
       [ 3.70775742, -1.36556388,  0.25387405]])

In [53]:
# integer random
result7 = np.random.randint(-10, 10, (5, 5))
print(result7)
print(result7.max())
print(result7.min())

[[ -4   4  -4  -3  -4]
 [  5  -4  -4  -6   7]
 [  9  -8   4  -5   7]
 [  8 -10   3  -8   1]
 [  1   8   5   5   3]]
9
-10


In [55]:
np.empty(10)


array([1.23780839e-311, 2.32210854e-322, 0.00000000e+000, 0.00000000e+000,
       1.05699242e-307, 1.16095484e-028, 2.59345444e+161, 3.40219075e-110,
       2.91237123e+257, 4.71294503e+257])

In [56]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [57]:
np.empty(5)

array([1., 1., 1., 1., 1.])